### PR TITLE
[chg] run.sh add -e to ash

### PR DESCRIPTION
**Pull request by baylanger**

### CODE REVIEW

**Comment by baylanger** [comment]
We need to exit on error because end users find errors for us. I don't mind waiting after this coming release.

**Comment by raphmur** [comment]
Does this option work also with bashio?
The Dockerfile in addon replaces the shebang here

**Comment by baylanger** [comment]
> Does this option work also with bashio? The Dockerfile in addon replaces the shebang here

AFAIK bashio imposes -e , right?  That's what I'm under impression or does it complain only on unbound variables? 🤔 

Anyhow ... we merge after release 0.2.0.

**Review by raphmur — APPROVED** [review]
Ok to merge whenever you want (before or after release 0.2.0)

**Pull request merged**
