### PR TITLE
Add eval working with ash

### PR DESCRIPTION
**Pull request by baylanger**
Hopefully the working example below with sh/ash doesn't make anyone nervous anymore:

```
# ash
# cat init-var.sh
export MQTT_IP=mqtt.xxxxxx.com
export MQTT_PORT=1883
export MQTT_USER=tesla-ble
export MQTT_PWD="a password; with & and "
# . ./init-var.sh
# cat mosquitto_pub
echo "\"$1\""
echo "\"$2\""
echo "\"$3\""
echo "\"$4\""
echo "\"$5\""
echo "\"$6\""
echo "\"$7\""
echo "\"$8\""
# export MOSQUITTO_PUB_BASE="./mosquitto_pub -h $MQTT_IP -p $MQTT_PORT -u '${MQTT_USER}' -P '${
MQTT_PWD}'"
#
# eval $MOSQUITTO_PUB_BASE
"-h"
"mqtt.xxxxxx.com"
"-p"
"1883"
"-u"
"tesla-ble"
"-P"
"a password; with & and "
```

### CODE REVIEW

**Comment by baylanger** [comment]
I made another test... I added a \" in the password and per the output, my guess is that it should work.

Hopefully the working example below with sh/ash doesn't make anyone nervous anymore:

```
# ash
# cat init-var.sh
export MQTT_IP=mqtt.xxxxxx.com
export MQTT_PORT=1883
export MQTT_USER=tesla-ble
export MQTT_PWD="a password; with & and \""
# . ./init-var.sh
# cat mosquitto_pub
echo "\"$1\""
echo "\"$2\""
echo "\"$3\""
echo "\"$4\""
echo "\"$5\""
echo "\"$6\""
echo "\"$7\""
echo "\"$8\""
# export MOSQUITTO_PUB_BASE="./mosquitto_pub -h $MQTT_IP -p $MQTT_PORT -u '${MQTT_USER}' -P '${MQTT_PWD}'"
#
# eval $MOSQUITTO_PUB_BASE
"-h"
"mqtt.xxxxxx.com"
"-p"
"1883"
"-u"
"tesla-ble"
"-P"
"a password; with & and ""
```

**Comment by iainbullock** [comment]
I'm ok to complete the review.

**Review by iainbullock — APPROVED** [review]
OK

**Comment by raphmur** [comment]
Seems right, thanks.

**Pull request merged**
