### PR TITLE
Add shell-fmt to pre-commit CI

### PR DESCRIPTION
**Pull request by epenet**

### CODE REVIEW

**Comment by baylanger** [comment]
@epenet I was slowly modding everything with 2 indent but you did the hard work!

Not sure for my colleagues but personally, I wasn't aware such hooks existed.

Minutes ago I made changes to the pre commit/push, will push to this branch.

There are conflicts, will try to fix them and merge this asap.

Thank you!

**Comment by baylanger** [comment]
I noticed you also changed logging level for some messages, it was on my mind to go over all of them and readjust them. Thank you to be ahead of me ;)

**Comment by baylanger** [comment]
Will manage this one in another PR.

```
In subroutines.sh line 15:
    tesla_ctrl_out=$(tesla-control -vin $vin -ble -key-name /share/tesla_blemqtt/${vin}_private.pem -key-file /share/tesla_ble_mqtt/${vin}_private.pem $@ 2>&1)
                                                                                                                                                       ^-- SC2068: Double quote array expansions to avoid re-splitting elements.
```

**Comment by epenet** [comment]
> I noticed you also changed logging level for some messages, it was on my mind to go over all of them and readjust them. Thank you to be ahead ;)

I'm not sure what you mean...
I didn't change any logging levels

**Review by baylanger — APPROVED** [review]
Looks good to me - thank you again!

**Pull request merged**
