### PR TITLE
Split core functions from two apps: HA addon & standalone docker + merge latest devs from tesla_ble_mqtt_docker

### PR DESCRIPTION
**Pull request by raphmur**
Structure has been changed to externalise core functions in a separate repo https://github.com/tesla-local-control/tesla_ble_mqtt_core/

It uses submodules to push the code to two repos:
- Standalone docker: https://github.com/tesla-local-control/tesla_ble_mqtt_docker. It contains all the docker specific files: docker-compose, Dockerfile, INSTALL
- HA Addon: https://github.com/tesla-local-control/tesla-local-control-addon. It contains all the HA specific files: DOCS, Dockerfile, config.yaml

image

Latest devs from these two repos have also been included:
- Support for up to 3 VINs
- File structure rework
- Externalize color logging functions

For contributors:

image

### CODE REVIEW

**Comment by iainbullock** [comment]
Unclear why both = and == works w/ sh 

I think = is assigning a new variable so always tests as true

It should be == for comparison of course

**Comment by iainbullock** [comment]
When building the docker image from the Dockerfile using Portainer, I get an error about /app/run.sh not having the right permissions. I had this when I did my original repo, it is caused by the scripts not being marked as executable in GitHub. @raphmur Can you run git update-index --chmod=-x  run.sh etc on the files, commit and push? I can do it if you wish

**Comment by raphmur** [comment]
Ok wildo in ~1hr
Chmodding in the Dockerfile is not working ?

**Comment by iainbullock** [comment]
Chmod in Dockerfile might work I am out so can't try it. From memory there isn't a CHMOD in the Dockerfile as it is. Might be a better way to do it as it's more visible and won't get missed when we add new scripts

**Comment by raphmur** [comment]
I run this `RUN chmod a+x /app/run.sh` in the dockerfile (for the addon).
Ran the command, but the files are already executable.

image

**Comment by raphmur** [comment]
Note I also had this kind of issues, but due to line endings... But if you go only through Github and Unix, it should be ok. However, if you Git Clone to Windows, then copy paste the files on Unix, you will have unexplained issues. --> Force LF line endings in your editor before building the image (only if you transit files through windows)

And the COPY command in Dockerfile is not super intuitive:
`COPY app /app/` --> Copies content of app in directory /app/
`COPY app /app` --> Copies content of app into something that depends on the existing structure.

See: https://chatgpt.com/share/61a56418-c343-4b71-b785-e6fc4579d093

image

Anyway, to be sure, if you want the content of app into the folder /app in the container, use `COPY app /app/`

Worth a try?

**Comment by iainbullock** [comment]
See original:
image

Core:
image

I have found not having 'Executable File' makes the docker container not run. This is despite having +x linux permisssions locally. I also recall having to change something in the script to get it to commit. It's not intuitive so I'm going to try doing CHMOD in the Dockerfile instead. I'll let you know 

I'm using Linux command line so no issues with end of line conversions in Windows.

**Comment by raphmur** [comment]
yeah indeed... done

**Comment by baylanger** [comment]
FYI exec mod isn't required on files that are sourced, they are considered "libraries".

Only the one that are run directly `/path/.... /file` or `./file/` needs it.

If calling a script like this `bash file` , that too would not require exec mod.

**Comment by baylanger** [comment]
#4 ready for merge

**Comment by baylanger** [comment]
> Unclear why both = and == works w/ sh
> 
> I think = is assigning a new variable so always tests as true
> 
> It should be == for comparison of course
>
That's what I thought too but ... not quite true, at least not sh(ash) and bash.

```
# test=test
# [ $test = "test" ] && echo yes || echo no
yes
# test=test1
# [ $test = "test" ] && echo yes || echo no
no
```

**Comment by baylanger** [comment]
> Note I also had this kind of issues, but due to line endings... But if you go only through Github and Unix, it should be ok. However, if you Git Clone to Windows, then copy paste the files on Unix, you will have unexplained issues. --> Force LF line endings in your editor before building the image (only if you transit files through windows)
>
dos2unix <file> removes - in-place - the inappropriate chars.

**Comment by baylanger** [comment]
Just merged #4 - now merging this one to main 🤞  We should be fine.

**Pull request merged**
